server:
  port: 8104

spring:
  application:
    name: appointment-service
  datasource:
    url: ${APPOINTMENT_DB_URL:jdbc:postgresql://localhost:5432/cloud_brain_medical?currentSchema=appointment}
    username: ${DB_USERNAME:cloudbrain}
    password: ${DB_PASSWORD:cloudbrain}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: appointment
    default-schema: appointment
    create-schemas: true
    locations: classpath:db/migration
