<template><main class="page"><div class="workspace">
  <header class="topbar"><div><p class="eyebrow">医技工作台</p><h1>{{ title }}</h1><p class="muted">仅显示 AI/规则分诊到当前医生的已缴费队列。</p></div><el-button @click="logout">退出</el-button></header>
  <section class="grid"><el-card class="span-7" shadow="never"><template #header>待执行队列</template>
    <el-table :data="orders" highlight-current-row @current-change="select"><el-table-column prop="queueNumber" label="队列" width="70"/><el-table-column prop="urgency" label="优先级" width="90"/><el-table-column prop="patientName" label="患者" width="100"/><el-table-column prop="projectName" label="项目"/><el-table-column prop="executionLocation" label="地点"/><el-table-column prop="equipmentId" label="设备" width="90"/><el-table-column prop="status" label="状态" width="110"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button v-if="row.status==='WAITING'" link type="primary" @click.stop="start(row)">开始</el-button><el-button v-if="row.status==='WAITING'" link @click.stop="miss(row)">过号</el-button></template></el-table-column></el-table>
  </el-card><el-card class="span-5" shadow="never"><template #header>结果与正式报告</template>
    <el-form label-position="top"><el-form-item label="当前医嘱"><el-input :model-value="current?.projectName??'请选择队列医嘱'" disabled/></el-form-item>
      <template v-if="role==='CHECK_DOCTOR'"><el-form-item label="CT/DICOM附件"><input type="file" @change="chooseFile"/></el-form-item><el-button :disabled="!file||!current" @click="uploadCt">上传并提交AI</el-button><el-button v-if="aiTaskId" @click="pollAi">刷新AI结果</el-button><p class="muted">AI任务：{{ aiStatus }}</p></template>
      <template v-if="role==='LAB_DOCTOR'"><el-form-item label="样本类型"><el-input v-model="lab.specimenType"/></el-form-item><el-form-item label="条码"><el-input v-model="lab.barcode"/></el-form-item><el-button :disabled="!current" @click="prepareSpecimen">登记并流转至分析</el-button><el-form-item label="指标名称"><el-input v-model="lab.itemName"/></el-form-item><el-form-item label="结果/单位"><el-input v-model="lab.value"/><el-input v-model="lab.unit"/></el-form-item><el-button :disabled="!specimenId" @click="saveLab">保存纵向指标</el-button></template>
      <el-form-item label="检查所见/执行过程"><el-input v-model="report.findings" type="textarea" :rows="3"/></el-form-item><el-form-item label="结论/结果"><el-input v-model="report.conclusion" type="textarea" :rows="3"/></el-form-item><el-form-item label="后续建议"><el-input v-model="report.advice" type="textarea" :rows="2"/></el-form-item>
      <el-button :disabled="!current" @click="draft">保存草稿</el-button><el-button type="success" :disabled="!current" @click="confirm">确认发布</el-button>
    </el-form></el-card></section>
</div></main></template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';import {ElMessage} from 'element-plus';import {useRouter} from 'vue-router';import {useAuthStore} from '../../store/auth';import {confirmReport,createReportDraft,createSpecimen,getMedicalOrders,missMedicalOrder,refreshAiTask,saveLabResults,startMedicalOrder,submitCt,transitionSpecimen,uploadAttachment,type MedicalOrder} from '../../api/medical-order';
const auth=useAuthStore(),router=useRouter(),role=computed(()=>auth.user?.role??''),titles:Record<string,string>={CHECK_DOCTOR:'检查医生工作台',LAB_DOCTOR:'检验医生工作台',DISPOSAL_DOCTOR:'处置医生工作台'},title=computed(()=>titles[role.value]??'医技工作台');
const orders=ref<MedicalOrder[]>([]),current=ref<MedicalOrder>(),file=ref<File>(),aiTaskId=ref(''),aiStatus=ref(''),specimenId=ref('');const report=reactive({findings:'',conclusion:'',advice:''});const lab=reactive({specimenType:'全血',barcode:`LAB-${Date.now()}`,itemName:'血红蛋白',value:'135',unit:'g/L'});
async function load(){orders.value=await getMedicalOrders()};function select(row?:MedicalOrder){current.value=row;report.findings='';report.conclusion='';report.advice=''}
async function start(row:MedicalOrder){await startMedicalOrder(row.id);ElMessage.success('已开始执行');await load()};async function miss(row:MedicalOrder){await missMedicalOrder(row.id);await load()}
function chooseFile(e:Event){file.value=(e.target as HTMLInputElement).files?.[0]};async function uploadCt(){if(!current.value||!file.value)return;const a=await uploadAttachment(current.value.id,file.value);const task=await submitCt(current.value.id,a.id);aiTaskId.value=task.externalTaskId;aiStatus.value=task.status;ElMessage.success('CT AI任务已提交')}
async function pollAi(){const task=await refreshAiTask(aiTaskId.value);aiStatus.value=task.status;if(task.status==='COMPLETED')ElMessage.success('AI报告草稿已生成，请刷新或人工填写后确认')}
async function prepareSpecimen(){if(!current.value)return;const s=await createSpecimen(current.value.id,lab.specimenType,lab.barcode);specimenId.value=s.id;for(const status of ['COLLECTED','RECEIVED','ANALYZING'])await transitionSpecimen(s.id,status);ElMessage.success('样本已进入分析阶段')}
async function saveLab(){if(!current.value)return;await saveLabResults(current.value.id,specimenId.value,[{itemCode:'HGB',itemName:lab.itemName,resultValue:lab.value,unit:lab.unit,referenceRange:'115-150',abnormalFlag:'NORMAL',createdByType:'HUMAN'}]);ElMessage.success('检验指标已保存')}
async function draft(){if(!current.value)return;await createReportDraft(current.value.id,report);ElMessage.success('报告草稿已保存')};async function confirm(){if(!current.value)return;await confirmReport(current.value.id,report);ElMessage.success('正式报告已发布，患者进入复诊队列');current.value=undefined;await load()}
function logout(){auth.signOut();router.push('/login')}onMounted(load)
</script>
