begin;

-- This script is intended for local/manual QA after Flyway has created schemas.
-- It seeds a repeatable dataset for:
-- 1. patient password login / sms login / registration
-- 2. real-name verification gate
-- 3. richer doctor / department / schedule browsing
-- 4. AI consultation -> recommended department -> online appointment booking
-- 5. pending payments / check-lab reports / disposal flow / prescriptions
--
-- Known password for all seeded accounts below: abc12345
-- BCrypt hash below matches abc12345.

insert into auth.user_account (
    id, username, password, phone, name, role, permissions, real_name_verified, created_at
)
values
    (
        'patient-test-verified-001',
        '13800000011',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13800000011',
        'Patient Verified',
        'PATIENT',
        'appointment:create,appointment:cancel,medical-record:read',
        true,
        now()
    ),
    (
        'patient-test-unverified-001',
        '13800000012',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13800000012',
        'Patient Unverified',
        'PATIENT',
        'appointment:create,appointment:cancel,medical-record:read',
        false,
        now()
    ),
    (
        'doctor-test-neuro-002',
        'doctor-neuro-02',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13700000021',
        'Doctor Neuro Li',
        'OUTPATIENT_DOCTOR',
        'appointment:read,appointment:skip,medical-record:read,medical-record:write,medical-order:create,prescription:create',
        true,
        now()
    ),
    (
        'doctor-test-neuro-003',
        'doctor-neuro-03',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13700000022',
        'Doctor Neuro Wang',
        'OUTPATIENT_DOCTOR',
        'appointment:read,appointment:skip,medical-record:read,medical-record:write,medical-order:create,prescription:create',
        true,
        now()
    ),
    (
        'doctor-test-general-002',
        'doctor-general-02',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13700000023',
        'Doctor General Zhao',
        'OUTPATIENT_DOCTOR',
        'appointment:read,appointment:skip,medical-record:read,medical-record:write,medical-order:create,prescription:create',
        true,
        now()
    ),
    (
        'doctor-test-general-003',
        'doctor-general-03',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13700000024',
        'Doctor General Sun',
        'OUTPATIENT_DOCTOR',
        'appointment:read,appointment:skip,medical-record:read,medical-record:write,medical-order:create,prescription:create',
        true,
        now()
    ),
    (
        'doctor-test-rehab-001',
        'doctor-rehab-01',
        '$2a$10$7NukEsugMLsxrPkaBLnhuOHHhSQg2RjHt4RiGYxJNx7pq9cyG6bL.',
        '13700000025',
        'Doctor Rehab Zhou',
        'OUTPATIENT_DOCTOR',
        'appointment:read,appointment:skip,medical-record:read,medical-record:write,medical-order:create,prescription:create',
        true,
        now()
    )
on conflict (username) do update
set password = excluded.password,
    phone = excluded.phone,
    name = excluded.name,
    role = excluded.role,
    permissions = excluded.permissions,
    real_name_verified = excluded.real_name_verified;

insert into patient.patient_profile (
    user_id, phone, name, id_card, gender, birth_date, real_name_verified, verified_at, created_at, updated_at
)
values
    (
        'patient-test-verified-001',
        '13800000011',
        'Patient Verified',
        '110101199003074512',
        'MALE',
        date '1990-03-07',
        true,
        now(),
        now(),
        now()
    ),
    (
        'patient-test-unverified-001',
        '13800000012',
        'Patient Unverified',
        null,
        null,
        null,
        false,
        null,
        now(),
        now()
    )
on conflict (user_id) do update
set phone = excluded.phone,
    name = excluded.name,
    id_card = excluded.id_card,
    gender = excluded.gender,
    birth_date = excluded.birth_date,
    real_name_verified = excluded.real_name_verified,
    verified_at = excluded.verified_at,
    updated_at = now();

insert into doctor.department (id, name, description, active)
values
    ('dept-rehab', 'Rehabilitation', 'Rehabilitation, acupuncture, dressing change and follow-up treatment', true)
on conflict (id) do update
set name = excluded.name,
    description = excluded.description,
    active = excluded.active;

insert into doctor.doctor (id, name, title, department_id, role_type, specialty, active)
values
    ('doctor-test-neuro-002', 'Doctor Neuro Li', 'Associate Chief Physician', 'dept-neuro', 'OUTPATIENT_DOCTOR', 'Vertigo, migraine, cerebrovascular follow-up', true),
    ('doctor-test-neuro-003', 'Doctor Neuro Wang', 'Attending Physician', 'dept-neuro', 'OUTPATIENT_DOCTOR', 'Sleep disorder, dizziness, neural rehabilitation follow-up', true),
    ('doctor-test-general-002', 'Doctor General Zhao', 'Associate Chief Physician', 'dept-general', 'OUTPATIENT_DOCTOR', 'Hypertension, diabetes, fever clinic', true),
    ('doctor-test-general-003', 'Doctor General Sun', 'Attending Physician', 'dept-general', 'OUTPATIENT_DOCTOR', 'Respiratory infection, chronic disease follow-up', true),
    ('doctor-test-rehab-001', 'Doctor Rehab Zhou', 'Attending Physician', 'dept-rehab', 'OUTPATIENT_DOCTOR', 'Acupuncture, dressing change, postoperative rehabilitation', true)
on conflict (id) do update
set name = excluded.name,
    title = excluded.title,
    department_id = excluded.department_id,
    role_type = excluded.role_type,
    specialty = excluded.specialty,
    active = excluded.active;

insert into doctor.doctor_schedule (
    id, doctor_id, department_id, work_date, period, capacity, status, suspension_reason, updated_at
)
values
    ('schedule-test-general-001', 'doctor-003', 'dept-general', current_date + 1, 'AFTERNOON', 12, 'PUBLISHED', null, now()),
    ('schedule-test-general-002-am', 'doctor-test-general-002', 'dept-general', current_date + 1, 'MORNING', 18, 'PUBLISHED', null, now()),
    ('schedule-test-general-002-pm', 'doctor-test-general-002', 'dept-general', current_date + 3, 'AFTERNOON', 16, 'PUBLISHED', null, now()),
    ('schedule-test-general-003-full', 'doctor-test-general-003', 'dept-general', current_date + 4, 'FULL_DAY', 22, 'PUBLISHED', null, now()),
    ('schedule-test-neuro-001', 'doctor-001', 'dept-neuro', current_date + 3, 'MORNING', 10, 'PUBLISHED', null, now()),
    ('schedule-test-neuro-002-am', 'doctor-test-neuro-002', 'dept-neuro', current_date + 2, 'MORNING', 14, 'PUBLISHED', null, now()),
    ('schedule-test-neuro-002-pm', 'doctor-test-neuro-002', 'dept-neuro', current_date + 2, 'AFTERNOON', 14, 'PUBLISHED', null, now()),
    ('schedule-test-neuro-003-am', 'doctor-test-neuro-003', 'dept-neuro', current_date + 5, 'MORNING', 12, 'PUBLISHED', null, now()),
    ('schedule-test-neuro-history-001', 'doctor-001', 'dept-neuro', current_date - 7, 'MORNING', 10, 'PUBLISHED', null, now()),
    ('schedule-test-rehab-001-am', 'doctor-test-rehab-001', 'dept-rehab', current_date + 2, 'MORNING', 10, 'PUBLISHED', null, now()),
    ('schedule-test-rehab-001-pm', 'doctor-test-rehab-001', 'dept-rehab', current_date + 6, 'AFTERNOON', 8, 'PUBLISHED', null, now())
on conflict (id) do update
set doctor_id = excluded.doctor_id,
    department_id = excluded.department_id,
    work_date = excluded.work_date,
    period = excluded.period,
    capacity = excluded.capacity,
    status = excluded.status,
    suspension_reason = excluded.suspension_reason,
    updated_at = now();

insert into appointment.slot_inventory (schedule_id, capacity, locked, booked)
values
    ('schedule-002', 18, 0, 4),
    ('schedule-test-general-001', 12, 0, 0),
    ('schedule-test-general-002-am', 18, 0, 2),
    ('schedule-test-general-002-pm', 16, 0, 1),
    ('schedule-test-general-003-full', 22, 0, 0),
    ('schedule-test-neuro-001', 10, 0, 1),
    ('schedule-test-neuro-002-am', 14, 0, 2),
    ('schedule-test-neuro-002-pm', 14, 0, 0),
    ('schedule-test-neuro-003-am', 12, 0, 0),
    ('schedule-test-neuro-history-001', 10, 0, 1),
    ('schedule-test-rehab-001-am', 10, 0, 1),
    ('schedule-test-rehab-001-pm', 8, 0, 0)
on conflict (schedule_id) do update
set capacity = excluded.capacity,
    locked = excluded.locked,
    booked = excluded.booked;

insert into appointment.appointment (
    id,
    schedule_id,
    patient_id,
    patient_name,
    doctor_id,
    doctor_name,
    department_id,
    department_name,
    visit_date,
    period,
    source,
    status,
    payment_status,
    payment_method,
    triage_summary,
    risk_level,
    recommended_department_id,
    queue_number,
    missed_count,
    created_at,
    paid_at,
    cancelled_at,
    lock_expires_at,
    business_no
)
values
    (
        'appt-test-future-001',
        'schedule-002',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Doctor Neuro',
        'dept-neuro',
        'Neurology',
        current_date + 1,
        'AFTERNOON',
        'ONLINE',
        'WAITING',
        'PAID',
        'WECHAT_TEST',
        'AI triage summary: recurring headache with mild dizziness; outpatient follow-up recommended.',
        'MEDIUM',
        'dept-neuro',
        1,
        0,
        now() - interval '1 day',
        now() - interval '1 day',
        null,
        null,
        'REGQA-FUTURE-001'
    ),
    (
        'appt-test-future-002',
        'schedule-test-neuro-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Doctor Neuro',
        'dept-neuro',
        'Neurology',
        current_date + 3,
        'MORNING',
        'ONLINE',
        'WAITING',
        'PAID',
        'WECHAT_TEST',
        'AI triage summary: follow-up for chronic headache management.',
        'LOW',
        'dept-neuro',
        1,
        0,
        now(),
        now(),
        null,
        null,
        'REGQA-FUTURE-002'
    ),
    (
        'appt-test-history-001',
        'schedule-test-neuro-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Doctor Neuro',
        'dept-neuro',
        'Neurology',
        current_date - 7,
        'MORNING',
        'ONLINE',
        'FINISHED',
        'PAID',
        'WECHAT_TEST',
        'AI triage summary: resolved headache episode.',
        'LOW',
        'dept-neuro',
        1,
        0,
        now() - interval '7 day',
        now() - interval '7 day',
        null,
        null,
        'REGQA-HISTORY-001'
    ),
    (
        'appt-test-pending-payment-001',
        'schedule-test-rehab-001-am',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-test-rehab-001',
        'Doctor Rehab Zhou',
        'dept-rehab',
        'Rehabilitation',
        current_date + 2,
        'MORNING',
        'ONLINE',
        'PENDING_PAYMENT',
        'UNPAID',
        null,
        'AI triage summary: neck and shoulder discomfort, dressing change and rehabilitation suggested.',
        'LOW',
        'dept-rehab',
        1,
        0,
        now(),
        null,
        null,
        now() + interval '30 minute',
        'REGQA-PENDING-001'
    )
on conflict (id) do update
set schedule_id = excluded.schedule_id,
    patient_id = excluded.patient_id,
    patient_name = excluded.patient_name,
    doctor_id = excluded.doctor_id,
    doctor_name = excluded.doctor_name,
    department_id = excluded.department_id,
    department_name = excluded.department_name,
    visit_date = excluded.visit_date,
    period = excluded.period,
    source = excluded.source,
    status = excluded.status,
    payment_status = excluded.payment_status,
    payment_method = excluded.payment_method,
    triage_summary = excluded.triage_summary,
    risk_level = excluded.risk_level,
    recommended_department_id = excluded.recommended_department_id,
    queue_number = excluded.queue_number,
    missed_count = excluded.missed_count,
    paid_at = excluded.paid_at,
    cancelled_at = excluded.cancelled_at,
    lock_expires_at = excluded.lock_expires_at,
    business_no = excluded.business_no;

insert into cashier.payment_order (
    id, business_type, business_id, patient_id, amount, payment_method, status, operator_id, created_at, paid_at, payment_scene
)
values
    ('pay-test-appt-future-001', 'APPOINTMENT', 'appt-test-future-001', 'patient-test-verified-001', 0.01, 'WECHAT_TEST', 'PAID', 'patient-test-verified-001', now() - interval '1 day', now() - interval '1 day', 'BUSINESS'),
    ('pay-test-appt-future-002', 'APPOINTMENT', 'appt-test-future-002', 'patient-test-verified-001', 0.01, 'WECHAT_TEST', 'PAID', 'patient-test-verified-001', now(), now(), 'BUSINESS'),
    ('pay-test-appt-history-001', 'APPOINTMENT', 'appt-test-history-001', 'patient-test-verified-001', 0.01, 'WECHAT_TEST', 'PAID', 'patient-test-verified-001', now() - interval '7 day', now() - interval '7 day', 'BUSINESS'),
    ('pay-test-appt-pending-001', 'APPOINTMENT', 'appt-test-pending-payment-001', 'patient-test-verified-001', 0.01, 'WECHAT_TEST', 'PENDING', 'patient-test-verified-001', now(), null, 'BUSINESS'),
    ('pay-test-order-check-paid-001', 'MEDICAL_ORDER', 'order-test-check-report-001', 'patient-test-verified-001', 260.00, 'WECHAT_TEST', 'PAID', 'staff-cashier-001', now() - interval '7 day', now() - interval '7 day', 'BUSINESS'),
    ('pay-test-order-lab-paid-001', 'MEDICAL_ORDER', 'order-test-lab-report-001', 'patient-test-verified-001', 35.00, 'WECHAT_TEST', 'PAID', 'staff-cashier-001', now() - interval '7 day', now() - interval '7 day', 'BUSINESS'),
    ('pay-test-order-disposal-paid-001', 'MEDICAL_ORDER', 'order-test-disposal-done-001', 'patient-test-verified-001', 25.00, 'WECHAT_TEST', 'PAID', 'staff-cashier-001', now() - interval '7 day', now() - interval '7 day', 'BUSINESS'),
    ('pay-test-order-check-pending-001', 'MEDICAL_ORDER', 'order-test-check-unpaid-001', 'patient-test-verified-001', 680.00, 'WECHAT_TEST', 'PENDING', 'patient-test-verified-001', now(), null, 'BUSINESS'),
    ('pay-test-order-lab-pending-001', 'MEDICAL_ORDER', 'order-test-lab-unpaid-001', 'patient-test-verified-001', 75.00, 'WECHAT_TEST', 'PENDING', 'patient-test-verified-001', now(), null, 'BUSINESS'),
    ('pay-test-order-disposal-pending-001', 'MEDICAL_ORDER', 'order-test-disposal-unpaid-001', 'patient-test-verified-001', 25.00, 'WECHAT_TEST', 'PENDING', 'patient-test-verified-001', now(), null, 'BUSINESS'),
    ('pay-test-rx-dispensed-001', 'PRESCRIPTION', 'rx-test-dispensed-001', 'patient-test-verified-001', 47.50, 'WECHAT_TEST', 'PAID', 'staff-cashier-001', now() - interval '7 day', now() - interval '7 day', 'BUSINESS'),
    ('pay-test-rx-pending-001', 'PRESCRIPTION', 'rx-test-pending-001', 'patient-test-verified-001', 18.50, 'WECHAT_TEST', 'PENDING', 'patient-test-verified-001', now(), null, 'BUSINESS'),
    ('pay-test-rx-waiting-001', 'PRESCRIPTION', 'rx-test-waiting-001', 'patient-test-verified-001', 29.00, 'WECHAT_TEST', 'PAID', 'staff-cashier-001', now() - interval '1 day', now() - interval '1 day', 'BUSINESS')
on conflict (business_type, business_id) do update
set patient_id = excluded.patient_id,
    amount = excluded.amount,
    payment_method = excluded.payment_method,
    status = excluded.status,
    operator_id = excluded.operator_id,
    paid_at = excluded.paid_at,
    payment_scene = excluded.payment_scene;

insert into medical_record.medical_record (
    id,
    appointment_id,
    patient_id,
    patient_name,
    doctor_id,
    doctor_name,
    department_name,
    visit_date,
    period,
    ai_triage_summary,
    ai_risk_level,
    chief_complaint,
    present_illness,
    diagnosis,
    treatment_plan,
    doctor_revision_note,
    status,
    created_at,
    updated_at,
    archived_at,
    past_history,
    allergy_history,
    physical_examination,
    preliminary_diagnosis,
    version,
    diagnosis_created_by_type,
    diagnosis_ai_record_id,
    diagnosis_confirmed_by,
    diagnosis_confirmed_at
)
values
    (
        'record-test-history-001',
        'appt-test-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Doctor Neuro',
        'Neurology',
        to_char(current_date - 7, 'YYYY-MM-DD'),
        'MORNING',
        'AI triage summary: resolved headache episode.',
        'LOW',
        'Intermittent headache for one week.',
        'Symptoms improved after rest and hydration.',
        'Primary headache, stable after treatment.',
        'Hydration, sleep optimization, outpatient follow-up if symptoms recur.',
        'Seeded QA medical record.',
        'ARCHIVED',
        now() - interval '7 day',
        now() - interval '6 day',
        now() - interval '6 day',
        'No major past history.',
        'No known drug allergy.',
        'Vitals stable, no focal neurological deficit.',
        'Likely tension-type headache.',
        1,
        'HUMAN',
        null,
        'doctor-001',
        now() - interval '6 day'
    )
on conflict (appointment_id) do update
set patient_id = excluded.patient_id,
    patient_name = excluded.patient_name,
    doctor_id = excluded.doctor_id,
    doctor_name = excluded.doctor_name,
    department_name = excluded.department_name,
    visit_date = excluded.visit_date,
    period = excluded.period,
    ai_triage_summary = excluded.ai_triage_summary,
    ai_risk_level = excluded.ai_risk_level,
    chief_complaint = excluded.chief_complaint,
    present_illness = excluded.present_illness,
    diagnosis = excluded.diagnosis,
    treatment_plan = excluded.treatment_plan,
    doctor_revision_note = excluded.doctor_revision_note,
    status = excluded.status,
    updated_at = excluded.updated_at,
    archived_at = excluded.archived_at,
    past_history = excluded.past_history,
    allergy_history = excluded.allergy_history,
    physical_examination = excluded.physical_examination,
    preliminary_diagnosis = excluded.preliminary_diagnosis,
    version = excluded.version,
    diagnosis_created_by_type = excluded.diagnosis_created_by_type,
    diagnosis_ai_record_id = excluded.diagnosis_ai_record_id,
    diagnosis_confirmed_by = excluded.diagnosis_confirmed_by,
    diagnosis_confirmed_at = excluded.diagnosis_confirmed_at;

insert into medical_order.medical_order (
    id, appointment_id, patient_id, patient_name, ordering_doctor_id, order_type,
    project_code, project_name, purpose, body_part, amount, payment_status, status,
    executor_id, executor_name, execution_location, equipment_id, queue_number, urgency,
    triage_created_by_type, triage_reasons, missed_count, result_data, result_summary,
    created_at, started_at, completed_at
)
values
    (
        'order-test-check-report-001',
        'appt-test-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'CHECK',
        'CT-HEAD',
        'Head CT',
        'Investigate recurrent headache cause',
        'Head',
        260.00,
        'PAID',
        'COMPLETED',
        'doctor-check-001',
        'Check Doctor',
        'Imaging Floor 2 CT Room',
        'CT-01',
        1,
        'ROUTINE',
        'HUMAN',
        'Neurology image screening',
        0,
        '{"finding":"No acute intracranial abnormality"}'::jsonb,
        'Head CT shows no acute bleeding or occupying lesion.',
        now() - interval '7 day',
        now() - interval '7 day' + interval '1 hour',
        now() - interval '7 day' + interval '2 hour'
    ),
    (
        'order-test-lab-report-001',
        'appt-test-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'LAB',
        'CBC',
        'Complete Blood Count',
        'Screen inflammatory markers',
        null,
        35.00,
        'PAID',
        'COMPLETED',
        'doctor-lab-001',
        'Lab Doctor',
        'Laboratory Floor 1',
        'LAB-01',
        2,
        'ROUTINE',
        'HUMAN',
        'Routine blood test',
        0,
        '{"cbc":"Within normal range"}'::jsonb,
        'Blood count is generally within normal range.',
        now() - interval '7 day',
        now() - interval '7 day' + interval '1 hour',
        now() - interval '7 day' + interval '2 hour'
    ),
    (
        'order-test-disposal-done-001',
        'appt-test-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'DISPOSAL',
        'DISP-INFUSION',
        'Infusion Treatment',
        'Symptomatic dehydration treatment',
        null,
        25.00,
        'PAID',
        'COMPLETED',
        'doctor-disposal-001',
        'Disposal Doctor',
        'Outpatient Building 3F Disposal Room',
        null,
        1,
        'ROUTINE',
        'HUMAN',
        'Infusion observation',
        0,
        '{"response":"Stable during infusion"}'::jsonb,
        'Infusion completed smoothly with no obvious adverse reaction.',
        now() - interval '7 day',
        now() - interval '7 day' + interval '2 hour',
        now() - interval '7 day' + interval '3 hour'
    ),
    (
        'order-test-disposal-wait-001',
        'appt-test-future-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'DISPOSAL',
        'DISP-INFUSION',
        'Dressing Change',
        'Follow-up wound dressing change',
        null,
        25.00,
        'PAID',
        'WAITING',
        'doctor-disposal-001',
        'Disposal Doctor',
        'Outpatient Building 3F Disposal Room',
        null,
        3,
        'ROUTINE',
        'HUMAN',
        'Queue after outpatient visit',
        0,
        null,
        null,
        now() - interval '1 day',
        null,
        null
    ),
    (
        'order-test-check-unpaid-001',
        'appt-test-future-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'CHECK',
        'MRI-BRAIN',
        'Brain MRI',
        'Further evaluation of chronic headache',
        'Brain',
        680.00,
        'UNPAID',
        'PENDING_PAYMENT',
        null,
        null,
        null,
        null,
        null,
        'ROUTINE',
        null,
        null,
        0,
        null,
        null,
        now(),
        null,
        null
    ),
    (
        'order-test-lab-unpaid-001',
        'appt-test-future-002',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'LAB',
        'LIVER',
        'Liver Function Panel',
        'Medication safety follow-up',
        null,
        75.00,
        'UNPAID',
        'PENDING_PAYMENT',
        null,
        null,
        null,
        null,
        null,
        'ROUTINE',
        null,
        null,
        0,
        null,
        null,
        now(),
        null,
        null
    ),
    (
        'order-test-disposal-unpaid-001',
        'appt-test-future-002',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'DISPOSAL',
        'DISP-INFUSION',
        'Infusion Observation',
        'Next-day infusion follow-up',
        null,
        25.00,
        'UNPAID',
        'PENDING_PAYMENT',
        null,
        null,
        null,
        null,
        null,
        'ROUTINE',
        null,
        null,
        0,
        null,
        null,
        now(),
        null,
        null
    )
on conflict (id) do update
set appointment_id = excluded.appointment_id,
    patient_id = excluded.patient_id,
    patient_name = excluded.patient_name,
    ordering_doctor_id = excluded.ordering_doctor_id,
    order_type = excluded.order_type,
    project_code = excluded.project_code,
    project_name = excluded.project_name,
    purpose = excluded.purpose,
    body_part = excluded.body_part,
    amount = excluded.amount,
    payment_status = excluded.payment_status,
    status = excluded.status,
    executor_id = excluded.executor_id,
    executor_name = excluded.executor_name,
    execution_location = excluded.execution_location,
    equipment_id = excluded.equipment_id,
    queue_number = excluded.queue_number,
    urgency = excluded.urgency,
    triage_created_by_type = excluded.triage_created_by_type,
    triage_reasons = excluded.triage_reasons,
    missed_count = excluded.missed_count,
    result_data = excluded.result_data,
    result_summary = excluded.result_summary,
    started_at = excluded.started_at,
    completed_at = excluded.completed_at;

insert into medical_order.medical_report (
    id, medical_order_id, report_type, status, findings, conclusion, advice, created_by_type,
    ai_task_id, ai_original_findings, ai_original_conclusion, modified_from_ai,
    confirmed_by, confirmed_at, rejected_by, rejected_at, rejection_reason, created_at, updated_at
)
values
    (
        'report-test-check-001',
        'order-test-check-report-001',
        'CHECK',
        'CONFIRMED',
        'No acute bleeding, no occupying lesion, ventricle shape is acceptable.',
        'Head CT shows no acute intracranial abnormality.',
        'Continue outpatient follow-up if headache recurs.',
        'HUMAN',
        null,
        null,
        null,
        false,
        'doctor-check-001',
        now() - interval '7 day' + interval '2 hour',
        null,
        null,
        null,
        now() - interval '7 day' + interval '1 hour',
        now() - interval '7 day' + interval '2 hour'
    ),
    (
        'report-test-lab-001',
        'order-test-lab-report-001',
        'LAB',
        'CONFIRMED',
        'WBC, RBC and platelet count are all within reference range.',
        'Complete blood count is generally within normal range.',
        'No urgent laboratory intervention required.',
        'HUMAN',
        null,
        null,
        null,
        false,
        'doctor-lab-001',
        now() - interval '7 day' + interval '2 hour',
        null,
        null,
        null,
        now() - interval '7 day' + interval '1 hour',
        now() - interval '7 day' + interval '2 hour'
    )
on conflict (medical_order_id) do update
set report_type = excluded.report_type,
    status = excluded.status,
    findings = excluded.findings,
    conclusion = excluded.conclusion,
    advice = excluded.advice,
    created_by_type = excluded.created_by_type,
    confirmed_by = excluded.confirmed_by,
    confirmed_at = excluded.confirmed_at,
    updated_at = excluded.updated_at;

insert into medical_record.medical_record_report_link (
    id, medical_record_id, medical_order_id, report_id, report_type, conclusion, confirmed_by, confirmed_at
)
values
    (
        '00000000-0000-0000-0000-000000000101',
        'record-test-history-001',
        'order-test-check-report-001',
        'report-test-check-001',
        'CHECK',
        'Head CT shows no acute intracranial abnormality.',
        'doctor-check-001',
        now() - interval '7 day' + interval '2 hour'
    ),
    (
        '00000000-0000-0000-0000-000000000102',
        'record-test-history-001',
        'order-test-lab-report-001',
        'report-test-lab-001',
        'LAB',
        'Complete blood count is generally within normal range.',
        'doctor-lab-001',
        now() - interval '7 day' + interval '2 hour'
    )
on conflict (medical_order_id, report_id) do nothing;

insert into pharmacy.prescription (
    id, prescription_no, appointment_id, medical_record_id, patient_id, patient_name, doctor_id,
    diagnosis, status, total_amount, payment_order_id, ai_assistance_id, ai_adoption_status,
    ai_revision_note, created_at, confirmed_at, paid_at, dispensed_at, returned_at,
    dispensed_by, returned_by, return_reason
)
values
    (
        'rx-test-dispensed-001',
        'RX-QA-001',
        'appt-test-history-001',
        'record-test-history-001',
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Primary headache, stable after treatment',
        'DISPENSED',
        47.50,
        'pay-test-rx-dispensed-001',
        null,
        'HUMAN_ONLY',
        null,
        now() - interval '7 day',
        now() - interval '7 day',
        now() - interval '7 day',
        now() - interval '6 day',
        null,
        'doctor-pharmacy-001',
        null,
        null
    ),
    (
        'rx-test-pending-001',
        'RX-QA-002',
        'appt-test-future-001',
        null,
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Headache follow-up medication',
        'PENDING_PAYMENT',
        18.50,
        null,
        null,
        'HUMAN_ONLY',
        null,
        now(),
        now(),
        null,
        null,
        null,
        null,
        null,
        null
    ),
    (
        'rx-test-waiting-001',
        'RX-QA-003',
        'appt-test-future-002',
        null,
        'patient-test-verified-001',
        'Patient Verified',
        'doctor-001',
        'Lipid control medication',
        'WAITING_DISPENSE',
        29.00,
        'pay-test-rx-waiting-001',
        null,
        'HUMAN_ONLY',
        null,
        now() - interval '1 day',
        now() - interval '1 day',
        now() - interval '1 day',
        null,
        null,
        null,
        null,
        null
    )
on conflict (id) do update
set prescription_no = excluded.prescription_no,
    appointment_id = excluded.appointment_id,
    medical_record_id = excluded.medical_record_id,
    patient_id = excluded.patient_id,
    patient_name = excluded.patient_name,
    doctor_id = excluded.doctor_id,
    diagnosis = excluded.diagnosis,
    status = excluded.status,
    total_amount = excluded.total_amount,
    payment_order_id = excluded.payment_order_id,
    ai_adoption_status = excluded.ai_adoption_status,
    ai_revision_note = excluded.ai_revision_note,
    confirmed_at = excluded.confirmed_at,
    paid_at = excluded.paid_at,
    dispensed_at = excluded.dispensed_at,
    returned_at = excluded.returned_at,
    dispensed_by = excluded.dispensed_by,
    returned_by = excluded.returned_by,
    return_reason = excluded.return_reason;

insert into pharmacy.prescription_item (
    id, prescription_id, drug_id, drug_name, quantity, dosage, usage, frequency, days, note, unit_price, amount
)
values
    ('rx-item-test-001', 'rx-test-dispensed-001', 'drug-aspirin', 'Aspirin Enteric Tablets', 1, '100mg', 'oral', 'once daily', 7, 'Take after meal', 18.50, 18.50),
    ('rx-item-test-002', 'rx-test-dispensed-001', 'drug-atorvastatin', 'Atorvastatin Calcium Tablets', 1, '20mg', 'oral', 'every night', 7, 'Take before sleep', 29.00, 29.00),
    ('rx-item-test-003', 'rx-test-pending-001', 'drug-aspirin', 'Aspirin Enteric Tablets', 1, '100mg', 'oral', 'once daily', 7, 'Continue after follow-up', 18.50, 18.50),
    ('rx-item-test-004', 'rx-test-waiting-001', 'drug-atorvastatin', 'Atorvastatin Calcium Tablets', 1, '20mg', 'oral', 'every night', 7, 'Stable long-term use', 29.00, 29.00)
on conflict (id) do update
set prescription_id = excluded.prescription_id,
    drug_id = excluded.drug_id,
    drug_name = excluded.drug_name,
    quantity = excluded.quantity,
    dosage = excluded.dosage,
    usage = excluded.usage,
    frequency = excluded.frequency,
    days = excluded.days,
    note = excluded.note,
    unit_price = excluded.unit_price,
    amount = excluded.amount;

commit;
