server:
  port: 8105

spring:
  application:
    name: medical-record-service
  datasource:
    url: ${MEDICAL_RECORD_DB_URL:jdbc:postgresql://localhost:5432/cloud_brain_medical?currentSchema=medical_record}
    username: ${DB_USERNAME:cloudbrain}
    password: ${DB_PASSWORD:cloudbrain}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: medical_record
    default-schema: medical_record
    create-schemas: true
    locations: classpath:db/migration
